export { normaliseRatingTables, relativityColor, relativityTextColor, tableStats, buildCartesianEntries } from "./ratingTableUtils"
export type { RatingTable } from "./ratingTableUtils"
export { StatsFooter } from "./StatsFooter"
export { OneWayEditor } from "./OneWayEditor"
export { TwoWayGrid } from "./TwoWayGrid"
